using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
	public class Course
	{
		[DatabaseGenerated(DatabaseGeneratedOption.None)]  //field is to be used a PK, but not generated by the DB, but filled manually by user.... 
		public int                     CourseID    { get; set; }

		public string                  Title       { get; set; }
		public int                     Credits     { get; set; }

		public ICollection<Enrollment> Enrollments { get; set; }
	}
}

